version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
